config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root to: "homes#index"
  resources :users
  resources :sessions
  resources :followers
  resources :homes, only: :index
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  # belongs_to :followers, class_name: User, foreign_key: :follower_id
  # belongs_to :followeds,  class_name: User, foreign_key: :followed_id
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # has_many :relationships, foreign_key: :followed_id
  # has_many :revers_relationships, class_name: Relationship, foreign_key: :follower_id
  # has_many :followers, through: :relationships
  # has_many :followeds, through: :revers_relationships

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: '/images/default-avatar-:style.png'
  validates_attachment :avatar,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_many :posts
  has_many :comments
  has_many :notifications

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email, :name
  validates_uniqueness_of :email, :name

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end


  def followers
    ids = Relationship.where(follower_id: self.id).pluck(:followed_id)
    User.where(id: ids)
  end

  def following
    ids = Relationship.where(followed_id: self.id).pluck(:follower_id)
    User.where(id: ids)
  end

  def add_follower(user_id)
    if self.id != user_id
      Relationship.create(follower_id: user_id, followed_id: self.id)
    end
  end

  def unfollow(user_id)
    Relationship.where(follower_id:  self.id, followed_id: user_id).destroy_all
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def update_
    # code here
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def create_notification(to, author, trackable)
    notification = to.notifications.build(user_id: to.id, author_id: author.id, trackable_id: trackable.id, trackable_type: trackable.title)
    notification.save
  end

  def destroy_notification
    current_user.notifications.destroy_all
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def requires_authentication
    puts '+++++++++++++++++++++++'
    puts current_user
    puts '+++++++++++++++++++++++'
      redirect_to log_in_path if current_user == nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_post
before_action :find_comment

  def new
    @comment = Comment.new
  end

  def index
    @comments = @post.comments
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      @post.comments << @comment
      redirect_to post_comments_path(@post), flash: {succes: 'Comment created'}
    else
      render :new
    end
  end

  def destroy
    if current_user.comments.where(id: @comment.id)
      @comment.destroy
      redirect_to :back, flash: {succes: 'Comment deleted'}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.find_by(id: params[:post_id])
  end

  def find_comment
    @comment = Comment.find_by(id: params[:id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def index
    @followeds = current_user.following
    @followers = current_user.followers
    respond_to do |format|
      format.html { }
      format.json { render json: @followers.to_json }
    end
    # ids = Relationship.where(follower_id: self.id).pluck(:id)
    # @followeds =  User.where(id: ids)
    # @followeds =  User.find_by(id: params[:id]).followers
  end

  def create
    followers = current_user.following
    if followers.include?(User.find_by(id: params[:id]))
      redirect_to followers_path, flash: {errors: "Error"}
    else
      current_user.add_follower(User.find_by(id: params[:id]).id)
      redirect_to followers_path
    end
  end

  def destroy
    User.find_by(id: params[:id]).unfollow(current_user.id)
    redirect_to followers_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :requires_authentication, only: :index
  after_action :destroy_notification, only: :index

  def index
    @following = current_user.following
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post
before_action :find_notification
after_action :add_nottification, only: :create

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, flash: {succes: 'Post created'}
    else
      render :new
    end
  end

  def update
    if @post.save
      redirect_to root_path, flash: {succes: 'Post updated'}
    end
  end

  def destroy
    if current_user.posts.where(id: @post.id )
      @post.destroy
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find_by(id: params[:id])
  end

  def find_notification
    @notification = Notification.find_by(id: params[:id])
  end

  def add_nottification
    current_user.followers.each do |user|
      create_notification(user, current_user, @post)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :requires_authentication, only: :index

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  def update
    current_user.update(user_params)
    #
    # respond_to do |format|
    #   format.html {}
    #   format.json { render json: current_user.to_json }
    # end
    redirect_to user_path(id: current_user.id)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="post">
  <div class="autor">
    <b>Author: </b><%= link_to @post.user.name, user_path(@post.user) %><br>
  </div>

  <div class="post_body">
    <b>Titile: </b><%= @post.title %><br>
    <b>Body: </b><%= @post.body %><br>
  </div>

  <div class="comment">
    <% @comments.each do |comment| %>
      <div class="comment_body">
        <%=  %>
        <b><%= comment.user.name %>: </b><%= comment.body %>
        <% if @post.comments.find_by(id: comment.id, user_id: current_user.id) %>
            <%= button_to "Delete comment", post_comment_path(post_id: @post.id, id: comment.id), method: :delete %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<h1>Create comment:</h1>

<%= form_for [@post, @comment] do |f| %>
    <% if @comment.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @comment.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/followers/index.html.erb
<div class="followers-container">
  <div class="list">
    <h2>People you are following:</h2>
    <% @followeds.each do |followed| %>
      <div class="user">
        <%= image_tag followed.avatar.url(:thumb) %>
        <br>
        <%= link_to followed.name, user_path(followed) %>
      </div>
    <% end %>
  </div>

  <div class="list">
    <h2>Your followers:</h2>
    <% @followers.each do |follower| %>
      <div class="user">
        <%= image_tag follower.avatar.url(:thumb) %>
        <br>
        <%= link_to follower.name, user_path(follower) %>
      </div>
    <% end %>
  </div>
</div>

app/views/homes/index.html.erb
<div class="news_feed">
  <h2>News feed:</h2>
  <div class="post_field">
    <div class="post">
      <% @following.each do |user| %>
        <% user.posts.each do |post| %>

          <div class="autor">
            <b>Author:</b><%= link_to user.name, user_path(user) %><br>
          </div>

          <div class="post_body">
            <b>Titile: </b><%= post.title %><br>
            <b>Body: </b><%= post.body %><br>

            <div class="more-info-button">
              <%= button_to "Create comment", new_post_comment_path(post_id: post.id), method: :get %>
              <% if user.posts.find_by(id: post.id, user_id: current_user.id) %>
                <tr>
                  <%= button_to "Update post", edit_post_path(id: post.id), method: :get %>
                  <%= button_to "Delete post", post_path(id: post.id), method: :delete %>
                </tr>
              <% end %>
            </div>
          </div>

          <div class="comment">
            <% post.comments.each do |comment| %>
              <div class="comment_body">
                <%=  %>
                <b><%= comment.user.name %>: </b><%= comment.body %>
                <% if post.comments.find_by(id: comment.id, user_id: current_user.id) %>
                    <%= button_to "Delete comment", post_comment_path(post_id: post.id, id: comment.id), method: :delete %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<div id="container">
  <div id="header">
    <head>
      <script type="text/javascript" src="js/jquery.js"></script>
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3/jquery.min.js"></script>
      <title>Tweet</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <div class="logo">
        <table>
        <tr>
          <td><%= image_tag("Logo.png", size: "100") %></td>
          <td><strong><%= @page_title || "T-W-E-E-T" %></strong></td>
        </tr>
        </table>
      </div>

      <div id="nav">
        <% if current_user %>
          <ul>
            <li><a href="#home"><%= link_to "Home", root_path, method: :get %></a></li>
            <li><a href="#news"><%= link_to "My relationship", followers_path, method: :get %></a></li>
            <li><a href="#contact"><%= link_to "My posts", user_path(id: current_user.id), method: :get %></a></li>
            <li><a href="#contact"><%= link_to "Users", users_path, method: :get %></a></li>
            <li style="float:right">
              <a class="active" href="#about">
                <%= link_to "Log out", log_out_path, method: :get %>
              </a>
            </li>
          </ul>
        <% end %>
      </div>
    </head>
  </div>

  <body class="<%= controller.controller_name %>">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <div id="main">
      <div id="main_left">
        <% if current_user != nil %>
          <div class="card">
            <div class="profile">
              <%= image_tag current_user.avatar.url(:thumb) %>
              <div class="border"></div>
            </div>
            <div class="name"><p><a href="#"><%= current_user.name %></a></p></div>
            <div class="email"><p><a href="#"><%= current_user.email %></a></p></div>

            <div class="numbers">

              <table id="stats">
                <tbody>
                <tr>
                  <td><%= current_user.posts.count%></td>
                  <td>POSTS</td>
                </tr>
                <tr>
                  <td><%= current_user.followers.count%></td>
                  <td>FOLLOWERS</td>
                </tr>
                <tr>
                  <td><%= current_user.following.count%></td>
                  <td>FOLLOWED</td>
                </tr>
                </tbody>
              </table>
              <div class="divider"></div>
            </div>

            <div class="notification">
              <% if current_user.notifications.count != 0 %>
                <%= link_to current_user.notifications.count, root_path, method: :get %>
                <%= image_tag("notification.png", size: "30") %>
              <% end %>

            </div>

            <div id="bupdate">
              <%= button_to "Update profile", edit_user_path(id: current_user.id), method: :get %>
            </div>
            </div>
      <% end %>

      </div>

      <div id="main_right">
        <%= yield %>
      </div>
    </div>
  </body>
  <div id="footer">
    © 2016 MichaelPekar, Inc
  </div>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @post.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_field :body %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
      <li><%= post.title %></li>
      <li><%= post.body %></li>
<% end %>
  <li><%= link_to "Create", new_post_path %></li>
</ul>

app/views/posts/new.html.erb
<h1>Create post:</h1>

<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @post.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/posts/show.html.erb
<h2><%=@post.title %></h2>
<%= @post.body %></br>
<ul>
    <% @post.comments.each do |comment| %>
      <li><%= comment.body %></br></li>
<% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
    <% if current_user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in current_user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
        <%= f.file_field :avatar %>
    </p>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<div class="card-container">
  <% @users.each do |user|%>
  <div class="card">

    <div class="profile">
      <%= image_tag user.avatar.url(:thumb) %>
      <div class="border"></div>
    </div>

    <div class="name">
      <%=link_to user.name, user_path(user) %>
    </div>

    <div id="follow">
      <% if current_user.following.include?(user) %>
          <%= button_to "Unfollow", follower_path(id: user.id), method: :delete %>
      <% else %>
          <%= button_to "Follow", controller: 'followers', action: 'create', method: :post, id: user.id %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
​<div class="session-container">
 <div id="signup">
   <%= form_for @user do |f| %>
     <div class="header">
       <h3>Sign Up</h3>
     </div>

     <div class="sep"></div>

     <div class="inputs">
       <div class="picture">
         <%= f.file_field :avatar %>
       </div>

       <div class="field">
         <%= f.label [:name, @user.errors[:name] ].join(' ') %><br />
         <%= f.text_field :name %>
       </div>

       <div class="field">
         <%= f.label [:email, @user.errors[:email] ].join(' ') %><br />
         <%= f.text_field :email %>
       </div>

       <div class="field">
         <%= f.label [:password, @user.errors[:password] ].join(' ') %><br />
         <%= f.password_field :password %>
       </div>

       <div class="field">
         <%= f.label [:password_confirmation, @user.errors[:password_confirmation] ].join(' ') %><br />
         <%= f.password_field :password_confirmation %>
       </div>

       <div class="accept">
         <%= f.submit "Sign Up" %>
       </div>

       <div class="link">
         <%= link_to "Log in", log_in_path, method: :get %>
       </div>
     </div>
   <% end %>
 </div>
</div>

app/views/users/show.html.erb
<div class="posts">
  <h2>Posts:</h2>
  <% if current_user.id == @user.id %>
    <div class="button">
      <%= button_to "Create post", new_post_path, method: :get %>
    </div>
  <% end %>

  <% if @user.posts != [] %>
    <div class="post">
      <% @user.posts.each do |post| %>
        <div class="post_body">
          <b>Titile:</b><%= post.title %><br>
          <b>Body:</b><%= post.body %><br>

          <div class="more-info-button">
            <%= button_to "Create comment", new_post_comment_path(post_id: post.id), method: :get %>
            <% if @user.posts.find_by(id: post.id, user_id: current_user.id) %>
              <tr>
                <%= button_to "Update post", edit_post_path(id: post.id), method: :get %>
                <%= button_to "Delete post", post_path(id: post.id), method: :delete %>
              </tr>
            <% end %>
          </div>
        </div>

        <div class="comment">
          <% post.comments.each do |comment| %>
            <div class="comment_body">
              <b><%= comment.user.name %>: </b><%= comment.body %>
              <% if post.comments.find_by(id: comment.id, user_id: current_user.id) %>
                  <%= button_to "Delete comment", post_comment_path(post_id: post.id, id: comment.id), method: :delete %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>"This user nothing written"</h3>
<% end %>
</div>